environment: production

global:
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  postgresql:
    host: postgresql
    port: 5432
    database: sausage_store
    username: sausage_store
    password: postgres-password
    jdbcUrl: jdbc:postgresql://postgresql:5432/sausage_store
  mongo:
    host: mongodb
    port: 27017
    rootUsername: root
    rootPassword: mongo-root-password
    database: reports
    username: report
    password: report-password
    appUri: mongodb://report:report-password@mongodb:27017/reports?authSource=reports

backend:
  image: kiberking/sausage-backend
  imageTag: latest
  replicas: 1
  revisionHistoryLimit: 15
  port: 8080
  reportPath: /logs/reports
  logPath: /logs
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 384Mi
  livenessProbe:
    path: /actuator/health
    initialDelaySeconds: 45
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6
  vpa:
    enabled: true
    updateMode: "Off"

backend-report:
  image: kiberking/sausage-backend-report
  imageTag: latest
  replicas: 1
  revisionHistoryLimit: 15
  port: 8080
  strategy:
    type: Recreate
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 200Mi
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    averageUtilization: 75

frontend:
  image: kiberking/sausage-frontend
  imageTag: latest
  replicas: 1
  revisionHistoryLimit: 15
  port: 8080
  servicePort: 80
  backendServicePort: 8080
  backendReportServicePort: 8080
  fqdn: front-kiber-king.2sem.students-projects.ru
  tlsSecretName: 2sem-students-projects-wildcard-secret
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

infra:
  postgresql:
    image: postgres:16-alpine
    storage: 1Gi
    storageClassName: ""
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 400m
        memory: 384Mi
  mongodb:
    image: mongo:7
    storage: 1Gi
    storageClassName: ""
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 400m
        memory: 384Mi
    initJob:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 300m
          memory: 512Mi
