apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-frontend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment | default "production" }}"
data:
  default.conf: |
    upstream backend {
      server {{ .Release.Name }}-backend:{{ .Values.backendServicePort }};
    }

    upstream backend_report {
      server {{ .Release.Name }}-backend-report:{{ .Values.backendReportServicePort }};
    }

    server {
      listen {{ .Values.port }};
      server_name _;
      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /api/reports/ {
        proxy_pass http://backend_report/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /reports/ {
        proxy_pass http://backend_report/reports/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location ~ ^/(products|orders|cart|catalog|actuator)(/|$) {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
