apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment | default "production" }}"
data:
  SPRING_DATASOURCE_URL: "{{ .Values.global.postgresql.jdbcUrl }}"
  SPRING_CLOUD_VAULT_ENABLED: "false"
  REPORT_PATH: "{{ .Values.reportPath }}"
  LOG_PATH: "{{ .Values.logPath }}"
