apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment | default "production" }}"
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "{{ .Values.global.postgresql.username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.global.postgresql.password }}"
  SPRING_DATA_MONGODB_URI: "{{ .Values.global.mongo.appUri }}"
